Fixed Code Execution in pm2-deploy
418sec/pm2-deploy pull request #1
Opened 2020-11-24 17:09 UTC by d3m0n-r00t

### 📊 Metadata *
Fixed ```Remote code execution``` in ```pm2-deploy```

#### Bounty URL: https://www.huntr.dev/bounties/1-npm-pm2-deploy/

### ⚙️ Description *
```pm2-deploy``` is a module that allows to do pm2 deploy. Documentation: http://pm2.keymetrics.io/docs/usage/deployment/

Affected versions of this package are vulnerable to Command Injection. It is possible to inject arbitrary commands by using malicious ```config``` in the ```spawn()``` function.

### 🐛 Proof of Concept (PoC) *
```javascript
var deployForEnv = require('pm2-deploy').deployForEnv;

var deployConfig = {
  prod: {
    "'; touch HACKED; # user": 'node',
    host: '127.0.0.1',
    ref: 'origin/master',
    repo: 'git@github.com:Asjidkalam/test-repo.git',
    path: '/var/www/test-dev'
  }
};

deployForEnv(deployConfig, 'prod', [], function (err, args) {
  if (err) {
    console.error('Deploy failed:', err.message);
    return console.error(err.stack);
  }
  console.log('Success!');
});
```
![pm2-poc](https://user-images.githubusercontent.com/29670330/100128013-b8cf3180-2ea5-11eb-9447-5126e1085f30.png)

### 🔥 Proof of Fix (PoF) *
![pm2-pof](https://user-images.githubusercontent.com/29670330/100128001-b66cd780-2ea5-11eb-94de-05da87844ba8.png)

### 👍 User Acceptance Testing (UAT)
Changed ```sh -c echo``` to just ```echo```. I didn't see any difference and the app seems to be working fine. 
Ps: I like open-source contribution.

2020-12-07 11:41 UTC, JamieSlome commented
@Unitech - it would be great to get your thoughts/opinions before we merge this in, cheers! 🍰

2020-12-10 12:15 UTC, Mik317 requested changes
Hi @d3m0n-r00t :smile:,
if the command to execute is something like `git add "test title"` it won't work anymore, also the second part of the `piping` is considered as an `argument` of the `echo` command while is a `sh script` which must be executed, so it would be better both avoid `space splitting` and instead `echo` just the first part and then execute the second part, so the `script` avoiding `pipelining` in `spawn` which doesn't allow you to use this type of command manipulation :+1: 

Cheers,
Mik

2020-12-11 08:36 UTC, d3m0n-r00t commented
Hi @Mik317, 
Sorry I didn't notice the `piping` at first. When I did a research on piping commands with `spawn`, the second process always exited with ```code 1```. So I updated the fix so that all the arguments are now passed as a list without concatenation.  Hope this would work. Inform me if any problem. 
Thank you

2020-12-17 12:13 UTC, Mik317 requested changes
Hi @d3m0n-r00t :smile:
I checked again but it seems to be vulnerable again to the `argument splitting` and since you provide the `sh` command and `-c` argument as first, it doesn't change the code from how it was previously (should be still vulnerable).

I think you should use more calls and save output of the first to avoid using the `sh` in `spawn` and therefore avoid any vulnerability or misfunctionality like `arg split` :+1: 

Cheers,
Mik

2020-12-18 17:20 UTC, d3m0n-r00t commented
Hi @Mik317,
Previously the command was given as a ```single``` element to spawn thus was vulnerable. But now every arguments is passed as an array. I think this could avoid ```RCE```. It works for me. 
![Screenshot 2020-12-18 223557](https://user-images.githubusercontent.com/29670330/102642016-0b3cfe80-4183-11eb-9705-cb4182d53e97.png)

Please verify and inform me if I am wrong.
Thank you

2020-12-28 18:41 UTC, Mik317 requested changes

2020-12-28 18:41 UTC, Mik317 commented on deploy.js
> +  cmd = cmd.split(' ');
Splitting arguments will still lead to `unfunctionalities` like when a `dir` like `"test test"` is supplied

2021-01-14 06:20 UTC, JamieSlome commented
@mzfr @mufeedvh @bbeale - would be good to get your thoughts here!

2021-01-19 07:35 UTC, JamieSlome commented
@d3m0n-r00t - closing this as it is going stale.

Feel free to open a new PR.

Thanks! 🍰

2021-01-19 07:35 UTC, closed without merging

2021-01-19 07:35 UTC, huntr-helper commented
Sorry d3m0n-r00t, we enjoyed reviewing your fix but it has not been selected this time. If this bounty has not been closed, please feel free to try again with a new pull request!

We appreciate your effort and look forward to reviewing more of your fixes in the future! 🔨😎

[Come join us on Discord](https://huntr.dev/discord)